 # Selenium Side Runner futtatása   
    
    - name: Run Tests
        run:
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" test.side
        
  # Nodejs telepítés
        
    - name: install Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
  # Selenium Side Runner telepítés
  
    - name: Install Selenium Side Runner
      run: |
         npm install -g selenium-side-runner
         
  # Chrome böngésző telepítése
  
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable 
      
  # Selenium webdriver telepítő program linuxra   
  
    - name: Install seleniumbase
      run: pip install seleniumbase
      
  # Chromedriver telepítés
  
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver

  

  
        
        


  
  

        

